### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by akkartik** [devhelpr/flowrunner-canvas#29]
I just tried to run `yarn install` and ran into this error:

```
src/components/canvas/index.tsx:38:25 - error TS2307: Cannot find module '../Taskbar' or its corresponding type declarations.

38 import { Taskbar } from '../Taskbar';
                           ~~~~~~~~~~~~
```

I'm running Nodejs version 14.17.6.

**Comment by devhelpr** [comment]
Hi Kartik,

Sorry about that.. I'll investigate and fix it tomorrow morning

Greetings,
Maikel

**Comment by akkartik** [comment]
Thank you. One way to improve things is to just specify in the Readme what version of Node you use.

**Comment by devhelpr** [comment]
Thanks for testing so far and reporting the issue, I am on Node 14.18.0 myself (I performed an update now). Just did a clean install of my project and didn't had any issues. I am still on Yarn 1.22.5, but not sure if that's the problem.

**Comment by devhelpr** [comment]
I just pushed an update which solved the compilation issue on windows wsl. Can you confirm that the project now compiles on your side? (no rush)
And whats also important to know: I am currently in the process of changing some things, so I will need to retest my test-case  because it could be that I broke some things

**Comment by akkartik** [comment]
Yes, the project now compiles! Thank you.

For my education, was the issue just that you're normally running on a case-insensitive file system? Just [this bit](https://github.com/devhelpr/flowrunner-canvas/commit/343df4827ddc7e29f877d983ada2b979ed093e0f#diff-4fcfd73c981a52edeebabd73ace09474849c5de05e9ee27489e69e4934de45a8)?
